name: YAML files

on:
  push:
    paths:
    - 'docs/**'
  pull_request:
    paths:
    - 'docs/**'

jobs:
  lint_speccy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
    - name: Lint with Speccy
      run: |
        find $PWD -name 'swagger.yaml' | while read FILE; do
          docker run -v ${FILE}:/swagger.yaml --rm wework/speccy lint /swagger.yaml;
        done;

  lint_openapi:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
    - name: Lint with openapi-spec-validator
      run: |
        find $PWD -name 'swagger.yaml' | while read FILE; do
          docker run -v ${FILE}:/swagger.yaml --rm p1c2u/openapi-spec-validator /swagger.yaml;
        done;
